# Generated by Django 3.1.1 on 2020-12-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('variedad', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagenes')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveceria.marca')),
            ],
        ),
    ]
